# Generated by Django 3.1 on 2023-11-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='state',
            new_name='county',
        ),
    ]
